# Generated by Django 4.1.3 on 2023-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_randevu'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='hastatcno',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
