# Generated by Django 4.1.3 on 2023-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_randevu_hastatcno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasta',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
